#!/usr/bin/env bash
# script installs nginx server, and creates a file with a message
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
