#!/usr/bin/env bash
# script installs nginx server, and creates a file with a message
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
