#!/usr/bin/env bash
#Configure your Nginx server so that 
#/redirect_me is redirecting to another page

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
