#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx

#configure firewall to allow request thru port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' |sudo tee /var/www/html/index.html

#creatibg  a wb page for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

#configuring nginx to 301 permanent redirect
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#configuring nginx for 404 eror display pagr
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart 
