#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

server_config =/
"
frontend blue-frontend
	bind *:80
	mode http
	default_backend blue-backend
backend blue-backend
	balance roundrobin
	server 66878-web-01 100.25.138.172:80 check
	server 66878-web-02 100.25.142.198:80 check
"

echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg

#ensures HAproxy can be managed via an init script 
echo "ENABLED=1" |sudo tee -a /etc/default/haproxy

sudo service haproxy restart
